### ISSUE TITLE
Weird values for yardsToEndzone

### ISSUE THREAD

**Issue by TomCasavant** [andrew-shackelford/Surrender-Index#9]
Sorry, not sure if you're still doing any development for the twitter bot, but

In my fork I'm seeing some weird values coming out of the nfl api for 'yardsToEndzone', It seems to be randomly deciding which endzone to report yardsToEndzone for which results in the check if the punt is from the opposing side of the field to fail.

In this image I've posted some of the debugging, in the top post it's a punt from the Carolina side of the field and it says yards to endzone  = 72, which is expected. 

In the bottom post it's Houston punting from their side of the field at the Houston 44 and it shows 44 yards to the houston endzone, which is unexpected and so it reports it as being on the Tennessee side of the field. Just wondering if you were seeing the same thing in your twitter bot, or if you've seen this before and have a solution for it (I haven't seen this sort of thing happen in the past month so it might be a new issue with the nfl API?)

![image](https://github.com/user-attachments/assets/6242ebfb-570c-4701-a2a8-6948011ba35e)

**Comment by andrew-shackelford** [comment]
Hey Tom, I actually saw this exact same thing this morning and had to take the bot down temporarily. I'm hoping to get some time to debug and fix it later this week and will let you know here when I do.

I have not seen anything like this before and it definitely is some kind of issue with the ESPN data -- so it's also possible they'll revert it and no changes will need to be made. One thing I noticed earlier when looking at the PBP data (on ESPN's website) is I see an entry at the end of each drive for an "Official Timeout", which I don't remember seeing before. It's possible this is also related to the issue since it creates a new play after the punt, but I'm not sure.
<img width="712" alt="Screenshot 2024-11-24 at 5 59 50 PM" src="https://github.com/user-attachments/assets/fd483445-fef0-4266-9ad5-3325aa04de2c">

Let me know if you find anything on your end, and either way I hope to have a fix sometime soon.

**Comment by TomCasavant** [comment]
Okay sweet! I thought I had messed something up when I ported the code and only noticed it now. 

My fix was to grab the Team IDs and Abbreviations from http://site.api.espn.com/apis/site/v2/sports/football/nfl/teams and use that to determine what side of the field they're on which seems to be working though I'm not sure if that's the best way to do it

https://github.com/TomCasavant/Surrender-Index/blob/c92616eeda6b87e0d4309845ed3cb749744c661b/surrender_index.py#L5-L30
```python
teams = { 
    '22': 'ARI', '1': 'ATL', '33': 'BAL', '2': 'BUF', '29': 'CAR',
    '3': 'CHI', '4': 'CIN', '5': 'CLE', '6': 'DAL', '7': 'DEN',
    '8': 'DET', '9': 'GB', '34': 'HOU', '11': 'IND', '30': 'JAX',
    '12': 'KC', '13': 'LV', '24': 'LAC', '14': 'LAR', '15': 'MIA',
    '16': 'MIN', '17': 'NE', '18': 'NO', '19': 'NYG', '20': 'NYJ',
    '21': 'PHI', '23': 'PIT', '25': 'SF', '26': 'SEA', '27': 'TB',
    '10': 'TEN', '28': 'WSH'
}

    def is_in_opposing_territory(play):
        team_id = str(play['start']['team']['id'])
        
        team_abbreviation = teams.get(team_id) # -> MIA
        
        possession_text = play['start']['possessionText'] # e.g. MIA 34
        
        if team_abbreviation and team_abbreviation in possession_text:
            # Team is on their own side
            return False
        else:
            # Team is on the opposing side
            return True
```

**Comment by andrew-shackelford** [comment]
Thanks! Your fix looks good so I'll incorporate it into mine as well :)

One thing to note is you may want to recalculate the historical indices for the current season since presumably there were some incorrect ones added when our bots had bad data earlier. You can modify the Historical Surrender Indices script to recalculate it using data from [here](https://github.com/nflverse/nflverse-data/releases/tag/pbp) which they update pretty often -- I'll probably rerun it Tuesday morning after they incorporate the data from MNF. I'm also happy to upload my results here then if you'd like to use them too.

Thanks again for reaching out and providing the fix!

**Comment by andrew-shackelford** [comment]
Looks like it worked!

Updated the repo with [this commit](https://github.com/andrew-shackelford/Surrender-Index/commit/dae122a75272f14724ed5631d1bbca9713bc6d0f). Let me know if you want the file with the indices for this season.

**Comment by TomCasavant** [comment]
If you already have those indices that'd make my life easier, thanks!

**Comment by andrew-shackelford** [comment]
Sure! I uploaded them to Google Drive [here](https://drive.google.com/file/d/15lXb514q5Ft4ozP3OZMyKpvxPY0Rqqtz/view?usp=sharing).
